locale: 'en-US'

spit_command_permission: 'funnyspits.use'

# Set to true if you want sound of llama spit to be played near the location
# of where the player has spat at else set to false.
spit_with_sound: true

# Intensity value of "spit" (number), value is required to be in the
# interval of numbers from 1 to 10.
spit_intensity: 1

# Damage that will be inflicted on the player/mob if it was spat.
# Must be set to 0 if you want next option to come in place
# (if the option has a value of true)!
spit_damage: 0

# Kills player/mob if it was spat if the value is true.
spit_kill: false

# Spit command cooldown (if value is zero, cooldown is cancelled).
spit_command_cooldown: 5

bonus_water_spits: 5

potion_effect_transmission_enabled: true

potion_effect_transmission_percentage: 40

autospit_enabled: true

# Permission for that player to be able to run plugin config reload command.
reload_command_permission: 'funnyspits.reload'